### ISSUE TITLE
Retrieving Data BUG

### ISSUE THREAD

**Issue by PrankAlien** [GamerKing195/Up2Date#10]
Spigot: 1.12.2
Plugin Version: latest
Description: The plugin is blocked on retrieved data plugins 37/38 97.37 %
Errors in console: https://hastebin.com/webocojiju.vbs

**Comment by GamerKing195** [comment]
Hey there I'm already aware of this bug, I'll be investigating and hopefully patching it this weekend

**Comment by GamerKing195** [comment]
Hello again, this issue should be fixed in version 1.2.5 found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=209508). Thank you again for your bug report, if you have any further problems with the plugin or this update fails to fix this error, please do not hesitate to create another problem or re-open this one, and I'll get to you as fast as I can.
