### ISSUE TITLE
Updating ID fails and doesn't update the proper ID.

### ISSUE THREAD

**Issue by magemaniac33** [GamerKing195/Up2Date#11]
I've noticed some plugins don't like updating the ID and it just reverts back and won't save the proper ID.
Ex: MythicDrops.
Correct Version: https://www.spigotmc.org/resources/mythicdrops.6114/
Wrong Version: https://www.spigotmc.org/resources/mythicdrops.5649/

![Current classes](https://i.gyazo.com/db65b445891de989cf367545d53773e9.png)

Not too sure why this occurs, but figured I'd mention it.

Progress \o/

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Updating ID's randomly failing](https://trello.com/c/IB04ZtKo/64-fix-updating-ids-randomly-failing)

**Comment by GamerKing195** [comment]
Will investigate this along with the two other bugs today.

**Comment by GamerKing195** [comment]
Hello, after looking into this it appears that the mythic drops plugin you want has the download type of zip which makes it incompatible with Up2Date. I would suggest messaging the author and asking him why the plugin needs to be downloaded as a zip as it is causing you an inconvenience.

Adding compatibility for zip files from Up2Date is next to impossible right now because of the difficulty in finding the correct jar and installing it, sorry :/
