### ISSUE TITLE
Update gives other filenames

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#16]
well
 when i update a plugin it many times takes the wrong version of spigot or changes the filename completely
for example :
Rewardpro.jar
after update it adds
RewardPro_Daily_Reward_+_Rank_Reward_+_Presentman-3.14.jar
and leaves the rewardpro.jar causing a dupe bug on startup/reload because the old one is not replaced or removed.

**Comment by GamerKing195** [comment]
Hey there this issue is currently known, it seems to only be with a very select few plugins and I haven't been able to find a reason as to why. I would recommend unlinking them from up2date as theyre currently incompatible likely due to something on the author of reward pro but I might be able to figure something out.

**Comment by mmuziek** [comment]
the rewardpro was an example it also happens with different other plugins

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
