### ISSUE TITLE
All Manually added Data Lost

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#19]
i worked over 4 hours yesterday entering all plugin id's from my used plugins such as rewardpro and CMI
and such.
now i restarted the server they are all gone even when i clicked SAVE TO FILE every time i made a change.
now i have to add them all over again and it does not even detect it correctly as REWARDPRO is just 1 plugin on spigot its a premium one and i am logged in into the plugin.
do i seriously need to start over again?

**Comment by GamerKing195** [comment]
Hey there, are you using a database or a flat file? If you're using a flat file and something happened to the plugindata.yml file or you're using an SQL database and something happened to the table being used that would also explain it.

Also, its a bit difficult for me to understand what this actually looks like ingame, imagery is always important when trying to fix a bug, normally I look for triggers & errors that occur when something like this happens otherwise it's nearly impossible to find out whats going on.

**Comment by GamerKing195** [comment]
^^ Misclicked sorry :P

**Comment by mmuziek** [comment]
im using a flat file at the moment. do i need to use Mysql ?
it also  reports all plugins as in need of updating even when its the correct version but with a . extra.

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
