### ISSUE TITLE
ERROR: Server returned HTTP response code: 403 for URL: https://spigotmc.org/

### ISSUE THREAD

**Issue by augesrob** [GamerKing195/Up2Date#22]
22.05 20:39:21 [Server] ERROR [U2D] ============== BEGIN ERROR ==============
22.05 20:39:21 [Server] ERROR [U2D] Error occurred while beginning automatic refresh.
22.05 20:39:21 [Server] ERROR [U2D] 
22.05 20:39:21 [Server] ERROR [U2D] PLUGIN VERSION: V1.4.2 (LATEST)
22.05 20:39:21 [Server] ERROR [U2D] 
22.05 20:39:21 [Server] ERROR [U2D] PLUGIN MESSAGE: HTTP Error while connecting to spigot.
22.05 20:39:21 [Server] INFO ERROR: Server returned HTTP response code: 403 for URL: https://spigotmc.org/
22.05 20:39:21 [Server] INFO Please wait 120 minutes for another automatic refresh.
22.05 20:39:21 [Server] INFO If this error repeats please report it to the developer at https://github.com/GamerKing195/Up2Date/issues
22.05 20:39:21 [Server] INFO Or on spigot at https://spigotmc.org/threads/284883/
22.05 20:39:21 [Server] ERROR [U2D] 
22.05 20:39:21 [Server] ERROR [U2D] ============== END ERROR ==============

**Comment by GamerKing195** [comment]
Hey there, this is a common connection issue between your server and Spigot, this means that Up2Date failed to retrieve information for a single plugin (or multiple if it was spammed) while it was refreshing. This is to be expected since the internet never works 100% of the time, however, if this is consistent, please let me know, and I will investigate further.

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
