### ISSUE TITLE
Setup retrieving data freezes

### ISSUE THREAD

**Issue by magemaniac33** [GamerKing195/Up2Date#9]
So after trying to set this up and getting authentication to work.
I keep running into the plugin stopping at the 2nd to last plugin over and over:
https://gyazo.com/7a8337b46155c4d179f9e11f72788c9b
https://gyazo.com/fea0de36c7cc2ad320b7d17868886ad9

Two different servers I tried and it just hangs there. Not sure why, went afk for over 30 minutes and nothing in console or anything while it searches.

**Comment by GamerKing195** [comment]
Hey there, thanks for the report, I'm aware of this bug and working on a fix as fast as my schedule will allow, you can monitor the progress on [Trello](https://trello.com/c/fGu80V9K)

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Up2Date setup consistently failing on 1 plugin](https://trello.com/c/fGu80V9K/59-fix-up2date-setup-consistently-failing-on-1-plugin)

**Comment by PrankAlien** [comment]
Also i have this Problem.

**Comment by GamerKing195** [comment]
Hello again, this issue should be fixed in version 1.2.5 found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=209508). Thank you again for your bug report, if you have any further problems with the plugin or this update fails to fix this error, please do not hesitate to create another problem or re-open this one, and I'll get to you as fast as I can.
